# Generated by Django 3.1.4 on 2020-12-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Who_is_clown', models.CharField(max_length=50, verbose_name='Clown')),
                ('Rodion', models.BigIntegerField(verbose_name='Times')),
            ],
        ),
    ]
